### ISSUE TITLE
Module syntax design

### ISSUE THREAD

**Issue by LennyPhoenix** [LennyPhoenix/bsinator#1]
Modules should be able to perform the following actions:
- Output messages to the user
- Take user input
- Install required dependencies
- Allow the user to select from optional dependencies

It may be easier to simply require the user to include a bootstrap script and a module list as opposed to a new language entirely. For example, a module may consist of a `mod_deps.json` containing a list of dependencies and hooks, and a selection of bash scripts that will be executed accordingly.

```json
{
  "pre": "pre.sh",
  "deps": [
  ],
  "post": "post.sh",
}
```

**Comment by LennyPhoenix** [comment]
Yaml may be a better choice as it supports comments

**Comment by LennyPhoenix** [comment]
Mockup yaml configuration:

```yaml
name: Neovim Setup
description: |
  Packages necessary for the neovim module.
dependencies:
- prompt: "Neovim module core packages"
  packages: [neovim, fzf, ripgrep, python-neovim]
- prompt: "Please select a terminal file browser:"
	packages: [nnn, ranger]
	requires: 1
pre: echo "Beginning neovim module installation..."
post: echo "Neovim module installation finished!"
```
